// Auto-generated from public/imported-product-images-renamed/produtos_imagens_renomeadas
export const GENERATED_PRODUCT_IMAGE_MANIFEST: Record<string, string[]> = {
  '895B': ['/imported-product-images-renamed/produtos_imagens_renomeadas/895B.jpg'],
  'A-07': ['/imported-product-images-renamed/produtos_imagens_renomeadas/A-07.jpg'],
  'A-2019': ['/imported-product-images-renamed/produtos_imagens_renomeadas/A-2019.jpg'],
  'A-286': ['/imported-product-images-renamed/produtos_imagens_renomeadas/A-286.jpg'],
  'A-331': ['/imported-product-images-renamed/produtos_imagens_renomeadas/A-331.jpg'],
  'A-388': ['/imported-product-images-renamed/produtos_imagens_renomeadas/A-388.jpg'],
  'A-505': ['/imported-product-images-renamed/produtos_imagens_renomeadas/A-505.jpg'],
  'A-607': ['/imported-product-images-renamed/produtos_imagens_renomeadas/A-607.jpg'],
  'A-607-A': ['/imported-product-images-renamed/produtos_imagens_renomeadas/A-607-A.jpg'],
  'A-607-F9': ['/imported-product-images-renamed/produtos_imagens_renomeadas/A-607-F9.jpg'],
  'A-607-P': ['/imported-product-images-renamed/produtos_imagens_renomeadas/A-607-P.jpg'],
  'A-607-Q': ['/imported-product-images-renamed/produtos_imagens_renomeadas/A-607-Q.jpg'],
  'A-607-Q-2': ['/imported-product-images-renamed/produtos_imagens_renomeadas/A-607-Q-2.jpg'],
  'A-607-Q-MC': ['/imported-product-images-renamed/produtos_imagens_renomeadas/A-607-Q-MC.jpg'],
  'A-607-T': ['/imported-product-images-renamed/produtos_imagens_renomeadas/A-607-T.jpg'],
  'A-607-W': ['/imported-product-images-renamed/produtos_imagens_renomeadas/A-607-W.jpg'],
  'A-607-W-PB': ['/imported-product-images-renamed/produtos_imagens_renomeadas/A-607-W-PB.jpg'],
  'A-607-X': ['/imported-product-images-renamed/produtos_imagens_renomeadas/A-607-X.jpg'],
  'A-607-Y': ['/imported-product-images-renamed/produtos_imagens_renomeadas/A-607-Y.jpg'],
  'A-607-Y-2': ['/imported-product-images-renamed/produtos_imagens_renomeadas/A-607-Y-2.jpg'],
  'A-686': ['/imported-product-images-renamed/produtos_imagens_renomeadas/A-686.jpg'],
  'A-707': ['/imported-product-images-renamed/produtos_imagens_renomeadas/A-707.jpg'],
  'A-708': ['/imported-product-images-renamed/produtos_imagens_renomeadas/A-708.jpg'],
  'A-808-5G': ['/imported-product-images-renamed/produtos_imagens_renomeadas/A-808-5G.jpg'],
  'A-905-5G': ['/imported-product-images-renamed/produtos_imagens_renomeadas/A-905-5G.jpg'],
  'A-908': ['/imported-product-images-renamed/produtos_imagens_renomeadas/A-908.jpg'],
  'A-908-5G': ['/imported-product-images-renamed/produtos_imagens_renomeadas/A-908-5G.jpg'],
  'A-918-TY': ['/imported-product-images-renamed/produtos_imagens_renomeadas/A-918-TY.jpg'],
  'A-FN06': ['/imported-product-images-renamed/produtos_imagens_renomeadas/A-FN06.jpg'],
  'A-P12': ['/imported-product-images-renamed/produtos_imagens_renomeadas/A-P12.jpg', '/imported-product-images-renamed/produtos_imagens_renomeadas/A-P12_1.jpg'],
  'A-W3': ['/imported-product-images-renamed/produtos_imagens_renomeadas/A-W3.jpg'],
  'AD-1088': ['/imported-product-images-renamed/produtos_imagens_renomeadas/AD-1088.jpg'],
  'AD-137': ['/imported-product-images-renamed/produtos_imagens_renomeadas/AD-137.jpg', '/imported-product-images-renamed/produtos_imagens_renomeadas/AD-137_1.jpg'],
  'AD-190': ['/imported-product-images-renamed/produtos_imagens_renomeadas/AD-190.jpg', '/imported-product-images-renamed/produtos_imagens_renomeadas/AD-190_1.jpg'],
  'AD-230': ['/imported-product-images-renamed/produtos_imagens_renomeadas/AD-230.jpg', '/imported-product-images-renamed/produtos_imagens_renomeadas/AD-230_1.jpg'],
  'AD-231': ['/imported-product-images-renamed/produtos_imagens_renomeadas/AD-231.jpg', '/imported-product-images-renamed/produtos_imagens_renomeadas/AD-231_1.jpg', '/imported-product-images-renamed/produtos_imagens_renomeadas/AD-231_2.jpg'],
  'AD-3088': ['/imported-product-images-renamed/produtos_imagens_renomeadas/AD-3088.jpg', '/imported-product-images-renamed/produtos_imagens_renomeadas/AD-3088_1.jpg'],
  'AD-3099': ['/imported-product-images-renamed/produtos_imagens_renomeadas/AD-3099.jpg', '/imported-product-images-renamed/produtos_imagens_renomeadas/AD-3099_1.jpg', '/imported-product-images-renamed/produtos_imagens_renomeadas/AD-3099_2.jpg', '/imported-product-images-renamed/produtos_imagens_renomeadas/AD-3099_3.jpg'],
  'AD-3188': ['/imported-product-images-renamed/produtos_imagens_renomeadas/AD-3188.jpg'],
  'AD-3199': ['/imported-product-images-renamed/produtos_imagens_renomeadas/AD-3199.jpg', '/imported-product-images-renamed/produtos_imagens_renomeadas/AD-3199_1.jpg'],
  'AD-520': ['/imported-product-images-renamed/produtos_imagens_renomeadas/AD-520.jpg'],
  'AD-6080': ['/imported-product-images-renamed/produtos_imagens_renomeadas/AD-6080.jpg'],
  'AD-8077': ['/imported-product-images-renamed/produtos_imagens_renomeadas/AD-8077.jpg'],
  'AD-8099': ['/imported-product-images-renamed/produtos_imagens_renomeadas/AD-8099.jpg', '/imported-product-images-renamed/produtos_imagens_renomeadas/AD-8099_1.jpg'],
  'AD-8106': ['/imported-product-images-renamed/produtos_imagens_renomeadas/AD-8106.jpg', '/imported-product-images-renamed/produtos_imagens_renomeadas/AD-8106_1.jpg', '/imported-product-images-renamed/produtos_imagens_renomeadas/AD-8106_2.jpg'],
  'AD-8399': ['/imported-product-images-renamed/produtos_imagens_renomeadas/AD-8399.jpg'],
  'AD-8528': ['/imported-product-images-renamed/produtos_imagens_renomeadas/AD-8528.jpg', '/imported-product-images-renamed/produtos_imagens_renomeadas/AD-8528_1.jpg'],
  'AD-8529': ['/imported-product-images-renamed/produtos_imagens_renomeadas/AD-8529.jpg', '/imported-product-images-renamed/produtos_imagens_renomeadas/AD-8529_1.jpg'],
  'AG-690': ['/imported-product-images-renamed/produtos_imagens_renomeadas/AG-690.jpg', '/imported-product-images-renamed/produtos_imagens_renomeadas/AG-690_1.jpg'],
  'AJ-3452': ['/imported-product-images-renamed/produtos_imagens_renomeadas/AJ-3452.jpg', '/imported-product-images-renamed/produtos_imagens_renomeadas/AJ-3452_1.jpg'],
  'AJ-3453': ['/imported-product-images-renamed/produtos_imagens_renomeadas/AJ-3453.jpg', '/imported-product-images-renamed/produtos_imagens_renomeadas/AJ-3453_1.jpg'],
  'AL-036': ['/imported-product-images-renamed/produtos_imagens_renomeadas/AL-036.jpg', '/imported-product-images-renamed/produtos_imagens_renomeadas/AL-036_1.jpg'],
  'AL-1010': ['/imported-product-images-renamed/produtos_imagens_renomeadas/AL-1010.jpg'],
  'AL-1050': ['/imported-product-images-renamed/produtos_imagens_renomeadas/AL-1050.jpg', '/imported-product-images-renamed/produtos_imagens_renomeadas/AL-1050_1.jpg'],
  'AL-2336': ['/imported-product-images-renamed/produtos_imagens_renomeadas/AL-2336.jpg'],
  'AL-2656': ['/imported-product-images-renamed/produtos_imagens_renomeadas/AL-2656.jpg', '/imported-product-images-renamed/produtos_imagens_renomeadas/AL-2656_1.jpg'],
  'AL-2659': ['/imported-product-images-renamed/produtos_imagens_renomeadas/AL-2659.jpg', '/imported-product-images-renamed/produtos_imagens_renomeadas/AL-2659_1.jpg'],
  'AL-2667': ['/imported-product-images-renamed/produtos_imagens_renomeadas/AL-2667.jpg', '/imported-product-images-renamed/produtos_imagens_renomeadas/AL-2667_1.jpg'],
  'AL-2669': ['/imported-product-images-renamed/produtos_imagens_renomeadas/AL-2669.jpg', '/imported-product-images-renamed/produtos_imagens_renomeadas/AL-2669_1.jpg'],
  'AL-2743': ['/imported-product-images-renamed/produtos_imagens_renomeadas/AL-2743.jpeg', '/imported-product-images-renamed/produtos_imagens_renomeadas/AL-2743.jpg'],
  'AL-3699': ['/imported-product-images-renamed/produtos_imagens_renomeadas/AL-3699.jpg', '/imported-product-images-renamed/produtos_imagens_renomeadas/AL-3699_1.jpg', '/imported-product-images-renamed/produtos_imagens_renomeadas/AL-3699_2.jpg'],
  'AL-3829': ['/imported-product-images-renamed/produtos_imagens_renomeadas/AL-3829.jpg', '/imported-product-images-renamed/produtos_imagens_renomeadas/AL-3829_1.jpg'],
  'AL-3916': ['/imported-product-images-renamed/produtos_imagens_renomeadas/AL-3916.jpg', '/imported-product-images-renamed/produtos_imagens_renomeadas/AL-3916_1.jpg'],
  'AL-3936': ['/imported-product-images-renamed/produtos_imagens_renomeadas/AL-3936.jpg', '/imported-product-images-renamed/produtos_imagens_renomeadas/AL-3936_1.jpg'],
  'AL-5G': ['/imported-product-images-renamed/produtos_imagens_renomeadas/AL-5G.jpg'],
  'AL-8391': ['/imported-product-images-renamed/produtos_imagens_renomeadas/AL-8391.jpg', '/imported-product-images-renamed/produtos_imagens_renomeadas/AL-8391_1.jpg'],
  'AL-8816-TY': ['/imported-product-images-renamed/produtos_imagens_renomeadas/AL-8816-TY.jpg'],
  'AL-8817-5G': ['/imported-product-images-renamed/produtos_imagens_renomeadas/AL-8817-5G.jpg'],
  'AL-A155': ['/imported-product-images-renamed/produtos_imagens_renomeadas/AL-A155.jpg', '/imported-product-images-renamed/produtos_imagens_renomeadas/AL-A155_1.jpg'],
  'AL-A230': ['/imported-product-images-renamed/produtos_imagens_renomeadas/AL-A230.jpg', '/imported-product-images-renamed/produtos_imagens_renomeadas/AL-A230_1.jpg'],
  'AL-B5207': ['/imported-product-images-renamed/produtos_imagens_renomeadas/AL-B5207.jpg'],
  'AL-B7760': ['/imported-product-images-renamed/produtos_imagens_renomeadas/AL-B7760.jpg', '/imported-product-images-renamed/produtos_imagens_renomeadas/AL-B7760_1.jpg'],
  'AL-B9001': ['/imported-product-images-renamed/produtos_imagens_renomeadas/AL-B9001.jpg'],
  'AL-BB20': ['/imported-product-images-renamed/produtos_imagens_renomeadas/AL-BB20.jpg', '/imported-product-images-renamed/produtos_imagens_renomeadas/AL-BB20_1.jpg'],
  'AL-C223': ['/imported-product-images-renamed/produtos_imagens_renomeadas/AL-C223.jpg', '/imported-product-images-renamed/produtos_imagens_renomeadas/AL-C223_1.jpg'],
  'AL-D890': ['/imported-product-images-renamed/produtos_imagens_renomeadas/AL-D890.jpg', '/imported-product-images-renamed/produtos_imagens_renomeadas/AL-D890_1.jpg'],
  'AL-E13': ['/imported-product-images-renamed/produtos_imagens_renomeadas/AL-E13.jpg'],
  'AL-E16': ['/imported-product-images-renamed/produtos_imagens_renomeadas/AL-E16.jpg'],
  'AL-E17': ['/imported-product-images-renamed/produtos_imagens_renomeadas/AL-E17.jpg'],
  'AL-L50': ['/imported-product-images-renamed/produtos_imagens_renomeadas/AL-L50.jpg', '/imported-product-images-renamed/produtos_imagens_renomeadas/AL-L50_1.jpg'],
  'AL-P9': ['/imported-product-images-renamed/produtos_imagens_renomeadas/AL-P9.jpg', '/imported-product-images-renamed/produtos_imagens_renomeadas/AL-P9_1.jpg'],
  'AL-S380': ['/imported-product-images-renamed/produtos_imagens_renomeadas/AL-S380.jpg', '/imported-product-images-renamed/produtos_imagens_renomeadas/AL-S380_1.jpg'],
  'AL-T2': ['/imported-product-images-renamed/produtos_imagens_renomeadas/AL-T2.jpg'],
  'AL-T3': ['/imported-product-images-renamed/produtos_imagens_renomeadas/AL-T3.jpg'],
  'AL-ZP33': ['/imported-product-images-renamed/produtos_imagens_renomeadas/AL-ZP33.jpg', '/imported-product-images-renamed/produtos_imagens_renomeadas/AL-ZP33_1.jpg'],
  'AU-4U': ['/imported-product-images-renamed/produtos_imagens_renomeadas/AU-4U.jpg', '/imported-product-images-renamed/produtos_imagens_renomeadas/AU-4U_1.jpg'],
  'C-231': ['/imported-product-images-renamed/produtos_imagens_renomeadas/C-231.jpg', '/imported-product-images-renamed/produtos_imagens_renomeadas/C-231_1.jpg'],
  'C-233': ['/imported-product-images-renamed/produtos_imagens_renomeadas/C-233.jpg', '/imported-product-images-renamed/produtos_imagens_renomeadas/C-233_1.jpg'],
  'F-060': ['/imported-product-images-renamed/produtos_imagens_renomeadas/F-060.jpg'],
  'F-060-BW': ['/imported-product-images-renamed/produtos_imagens_renomeadas/F-060-BW.jpg'],
  'F-070': ['/imported-product-images-renamed/produtos_imagens_renomeadas/F-070.jpg'],
  'G9S': ['/imported-product-images-renamed/produtos_imagens_renomeadas/G9S.jpg'],
  'I11': ['/imported-product-images-renamed/produtos_imagens_renomeadas/i11.jpeg', '/imported-product-images-renamed/produtos_imagens_renomeadas/i11.jpg'],
  'I11-2': ['/imported-product-images-renamed/produtos_imagens_renomeadas/i11-2.jpg'],
  'I12': ['/imported-product-images-renamed/produtos_imagens_renomeadas/i12.jpg'],
  'I7MINI': ['/imported-product-images-renamed/produtos_imagens_renomeadas/i7mini.jpg'],
  'I7S': ['/imported-product-images-renamed/produtos_imagens_renomeadas/i7s.jpg'],
  'I9S': ['/imported-product-images-renamed/produtos_imagens_renomeadas/i9s.jpg'],
  'J-60-A': ['/imported-product-images-renamed/produtos_imagens_renomeadas/J-60-A.jpg'],
  'J-60-AIR31': ['/imported-product-images-renamed/produtos_imagens_renomeadas/J-60-AIR31.jpg'],
  'J-60-AIR39': ['/imported-product-images-renamed/produtos_imagens_renomeadas/J-60-AIR39.jpg'],
  'J-60-D': ['/imported-product-images-renamed/produtos_imagens_renomeadas/J-60-D.jpg'],
  'J-60-G': ['/imported-product-images-renamed/produtos_imagens_renomeadas/J-60-G.jpg'],
  'J-60-L': ['/imported-product-images-renamed/produtos_imagens_renomeadas/J-60-L.jpg'],
  'J-60-P': ['/imported-product-images-renamed/produtos_imagens_renomeadas/J-60-P.jpg'],
  'J-60-R': ['/imported-product-images-renamed/produtos_imagens_renomeadas/J-60-R.jpg'],
  'J-60-U': ['/imported-product-images-renamed/produtos_imagens_renomeadas/J-60-U.jpg'],
  'J-60-Y': ['/imported-product-images-renamed/produtos_imagens_renomeadas/J-60-Y.jpg'],
  'J-70-PRO-B': ['/imported-product-images-renamed/produtos_imagens_renomeadas/J-70-PRO-B.jpg', '/imported-product-images-renamed/produtos_imagens_renomeadas/J-70-PRO-B_1.jpg'],
  'J-70-PRO-B-2': ['/imported-product-images-renamed/produtos_imagens_renomeadas/J-70-PRO-B-2.jpg'],
  'J-80-PRO': ['/imported-product-images-renamed/produtos_imagens_renomeadas/J-80-PRO.jpg'],
  'J-85-PRO': ['/imported-product-images-renamed/produtos_imagens_renomeadas/J-85-PRO.jpg'],
  'J-88-PRO': ['/imported-product-images-renamed/produtos_imagens_renomeadas/J-88-PRO.jpg'],
  'J-99-PRO': ['/imported-product-images-renamed/produtos_imagens_renomeadas/J-99-PRO.jpg', '/imported-product-images-renamed/produtos_imagens_renomeadas/J-99-PRO_1.jpg'],
  'J930': ['/imported-product-images-renamed/produtos_imagens_renomeadas/J930.jpg'],
  'JD-107': ['/imported-product-images-renamed/produtos_imagens_renomeadas/JD-107.jpg', '/imported-product-images-renamed/produtos_imagens_renomeadas/JD-107_1.jpg', '/imported-product-images-renamed/produtos_imagens_renomeadas/JD-107_2.jpg'],
  'JD-108': ['/imported-product-images-renamed/produtos_imagens_renomeadas/JD-108.jpg', '/imported-product-images-renamed/produtos_imagens_renomeadas/JD-108_1.jpg', '/imported-product-images-renamed/produtos_imagens_renomeadas/JD-108_2.jpg'],
  'JD-30': ['/imported-product-images-renamed/produtos_imagens_renomeadas/JD-30.jpg', '/imported-product-images-renamed/produtos_imagens_renomeadas/JD-30_1.jpg', '/imported-product-images-renamed/produtos_imagens_renomeadas/JD-30_2.jpg'],
  'JD-31': ['/imported-product-images-renamed/produtos_imagens_renomeadas/JD-31.jpg', '/imported-product-images-renamed/produtos_imagens_renomeadas/JD-31_1.jpg'],
  'JD-32': ['/imported-product-images-renamed/produtos_imagens_renomeadas/JD-32.jpg', '/imported-product-images-renamed/produtos_imagens_renomeadas/JD-32_1.jpg'],
  'JD-35': ['/imported-product-images-renamed/produtos_imagens_renomeadas/JD-35.jpg', '/imported-product-images-renamed/produtos_imagens_renomeadas/JD-35_1.jpg'],
  'K98': ['/imported-product-images-renamed/produtos_imagens_renomeadas/K98.jpg'],
  'LYF-01': ['/imported-product-images-renamed/produtos_imagens_renomeadas/LYF-01.jpg', '/imported-product-images-renamed/produtos_imagens_renomeadas/LYF-01_1.jpg'],
  'LYF-02': ['/imported-product-images-renamed/produtos_imagens_renomeadas/LYF-02.jpg', '/imported-product-images-renamed/produtos_imagens_renomeadas/LYF-02_1.jpg'],
  'LYF-03': ['/imported-product-images-renamed/produtos_imagens_renomeadas/LYF-03.jpg', '/imported-product-images-renamed/produtos_imagens_renomeadas/LYF-03_1.jpg'],
  'LYF-05': ['/imported-product-images-renamed/produtos_imagens_renomeadas/LYF-05.jpg', '/imported-product-images-renamed/produtos_imagens_renomeadas/LYF-05_1.jpg'],
  'LYF-10': ['/imported-product-images-renamed/produtos_imagens_renomeadas/LYF-10.jpg', '/imported-product-images-renamed/produtos_imagens_renomeadas/LYF-10_1.jpg'],
  'LYF-14': ['/imported-product-images-renamed/produtos_imagens_renomeadas/LYF-14.jpg', '/imported-product-images-renamed/produtos_imagens_renomeadas/LYF-14_1.jpg'],
  'LYF-15': ['/imported-product-images-renamed/produtos_imagens_renomeadas/LYF-15.jpg', '/imported-product-images-renamed/produtos_imagens_renomeadas/LYF-15_1.jpg'],
  'LYF-20': ['/imported-product-images-renamed/produtos_imagens_renomeadas/LYF-20.jpg', '/imported-product-images-renamed/produtos_imagens_renomeadas/LYF-20_1.jpg'],
  'M-303': ['/imported-product-images-renamed/produtos_imagens_renomeadas/M-303.jpg', '/imported-product-images-renamed/produtos_imagens_renomeadas/M-303_1.jpg'],
  'PN-951': ['/imported-product-images-renamed/produtos_imagens_renomeadas/PN-951.jpg'],
  'PN-952': ['/imported-product-images-renamed/produtos_imagens_renomeadas/PN-952.jpg'],
  'RS13': ['/imported-product-images-renamed/produtos_imagens_renomeadas/RS13.jpg'],
  'RS15': ['/imported-product-images-renamed/produtos_imagens_renomeadas/RS15.jpg'],
  'T10': ['/imported-product-images-renamed/produtos_imagens_renomeadas/T10.jpg', '/imported-product-images-renamed/produtos_imagens_renomeadas/T10_1.jpg'],
  'T11': ['/imported-product-images-renamed/produtos_imagens_renomeadas/T11.jpg'],
  'TX04': ['/imported-product-images-renamed/produtos_imagens_renomeadas/TX04.jpg'],
  'U60': ['/imported-product-images-renamed/produtos_imagens_renomeadas/U60.jpg'],
  'ZQ-01': ['/imported-product-images-renamed/produtos_imagens_renomeadas/ZQ-01.jpg', '/imported-product-images-renamed/produtos_imagens_renomeadas/ZQ-01_1.jpg'],
};
