export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      categorias: {
        Row: {
          id: string;
          nome: string;
          slug: string;
          descricao: string | null;
          imagem_url: string | null;
          order_index: number;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          nome: string;
          slug: string;
          descricao?: string | null;
          imagem_url?: string | null;
          order_index?: number;
          is_active?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          nome?: string;
          slug?: string;
          descricao?: string | null;
          imagem_url?: string | null;
          order_index?: number;
          is_active?: boolean;
          created_at?: string;
        };
      };
      produtos: {
        Row: {
          id: string;
          nome: string;
          slug: string;
          descricao: string | null;
          sku: string;
          categoria_id: string | null;
          preco_unitario: number;
          preco_caixa: number | null;
          preco_promocional_unitario: number | null;
          preco_promocional_caixa: number | null;
          quantidade_por_caixa: number | null;
          peso_caixa: number | null;
          dimensoes_caixa: Json | null;
          estoque_unitario: number;
          estoque_caixa: number;
          imagem_principal: string;
          galeria_imagens: string[] | null;
          video_url: string | null;
          is_novo: boolean;
          is_promocao: boolean;
          is_mais_vendido: boolean;
          is_destaque: boolean;
          destaque_home: boolean | null;
          related_product_ids: string[] | null;
          tipo_catalogo: 'UNITARIO' | 'CAIXA_FECHADA' | 'AMBOS';
          meta_title: string | null;
          meta_description: string | null;
          is_active: boolean;
          visualizacoes: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          nome: string;
          slug: string;
          descricao?: string | null;
          sku: string;
          categoria_id?: string | null;
          preco_unitario: number;
          preco_caixa?: number | null;
          preco_promocional_unitario?: number | null;
          preco_promocional_caixa?: number | null;
          quantidade_por_caixa?: number | null;
          peso_caixa?: number | null;
          dimensoes_caixa?: Json | null;
          estoque_unitario?: number;
          estoque_caixa?: number;
          imagem_principal: string;
          galeria_imagens?: string[] | null;
          video_url?: string | null;
          is_novo?: boolean;
          is_promocao?: boolean;
          is_mais_vendido?: boolean;
          is_destaque?: boolean;
          destaque_home?: boolean | null;
          related_product_ids?: string[] | null;
          tipo_catalogo: 'UNITARIO' | 'CAIXA_FECHADA' | 'AMBOS';
          meta_title?: string | null;
          meta_description?: string | null;
          is_active?: boolean;
          visualizacoes?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          nome?: string;
          slug?: string;
          descricao?: string | null;
          sku?: string;
          categoria_id?: string | null;
          preco_unitario?: number;
          preco_caixa?: number | null;
          preco_promocional_unitario?: number | null;
          preco_promocional_caixa?: number | null;
          quantidade_por_caixa?: number | null;
          peso_caixa?: number | null;
          dimensoes_caixa?: Json | null;
          estoque_unitario?: number;
          estoque_caixa?: number;
          imagem_principal?: string;
          galeria_imagens?: string[] | null;
          video_url?: string | null;
          is_novo?: boolean;
          is_promocao?: boolean;
          is_mais_vendido?: boolean;
          is_destaque?: boolean;
          destaque_home?: boolean | null;
          related_product_ids?: string[] | null;
          tipo_catalogo?: 'UNITARIO' | 'CAIXA_FECHADA' | 'AMBOS';
          meta_title?: string | null;
          meta_description?: string | null;
          is_active?: boolean;
          visualizacoes?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      pedidos: {
        Row: {
          id: string;
          numero_pedido: string;
          cliente_nome: string | null;
          cliente_telefone: string | null;
          cliente_email: string | null;
          tipo_catalogo: 'UNITARIO' | 'CAIXA_FECHADA';
          subtotal: number;
          desconto_valor: number;
          desconto_percentual: number;
          total: number;
          itens: Json;
          endereco: Json | null;
          checkout_token: string | null;
          user_id: string | null;
          original_total: number | null;
          coupon_code: string | null;
          coupon_discount_type: string | null;
          coupon_discount_value: number | null;
          abandoned_cart_id: string | null;
          status: string;
          status_pedido: string | null;
          status_pagamento: string | null;
          forma_pagamento: string | null;
          gateway: string | null;
          payment_id_gateway: string | null;
          external_reference: string | null;
          pix_qr_code: string | null;
          pix_copia_cola: string | null;
          whatsapp_enviado: boolean;
          mensagem_whatsapp: string | null;
          payment_gateway_response: Json | null;
          status_gateway_detalhe: string | null;
          paid_at: string | null;
          created_at: string;
          updated_at: string | null;
        };
        Insert: {
          id?: string;
          numero_pedido: string;
          cliente_nome?: string | null;
          cliente_telefone?: string | null;
          cliente_email?: string | null;
          tipo_catalogo: 'UNITARIO' | 'CAIXA_FECHADA';
          subtotal: number;
          desconto_valor?: number;
          desconto_percentual?: number;
          total: number;
          itens: Json;
          endereco?: Json | null;
          checkout_token?: string | null;
          user_id?: string | null;
          original_total?: number | null;
          coupon_code?: string | null;
          coupon_discount_type?: string | null;
          coupon_discount_value?: number | null;
          abandoned_cart_id?: string | null;
          status?: string;
          status_pedido?: string | null;
          status_pagamento?: string | null;
          forma_pagamento?: string | null;
          gateway?: string | null;
          payment_id_gateway?: string | null;
          external_reference?: string | null;
          pix_qr_code?: string | null;
          pix_copia_cola?: string | null;
          whatsapp_enviado?: boolean;
          mensagem_whatsapp?: string | null;
          payment_gateway_response?: Json | null;
          status_gateway_detalhe?: string | null;
          paid_at?: string | null;
          created_at?: string;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          numero_pedido?: string;
          cliente_nome?: string | null;
          cliente_telefone?: string | null;
          cliente_email?: string | null;
          tipo_catalogo?: 'UNITARIO' | 'CAIXA_FECHADA';
          subtotal?: number;
          desconto_valor?: number;
          desconto_percentual?: number;
          total?: number;
          itens?: Json;
          endereco?: Json | null;
          checkout_token?: string | null;
          user_id?: string | null;
          original_total?: number | null;
          coupon_code?: string | null;
          coupon_discount_type?: string | null;
          coupon_discount_value?: number | null;
          abandoned_cart_id?: string | null;
          status?: string;
          status_pedido?: string | null;
          status_pagamento?: string | null;
          forma_pagamento?: string | null;
          gateway?: string | null;
          payment_id_gateway?: string | null;
          external_reference?: string | null;
          pix_qr_code?: string | null;
          pix_copia_cola?: string | null;
          whatsapp_enviado?: boolean;
          mensagem_whatsapp?: string | null;
          payment_gateway_response?: Json | null;
          status_gateway_detalhe?: string | null;
          paid_at?: string | null;
          created_at?: string;
          updated_at?: string | null;
        };
      };
      pagamentos: {
        Row: {
          id: string;
          pedido_id: string | null;
          numero_pedido: string;
          gateway: string;
          forma_pagamento: string;
          payment_id_gateway: string;
          external_reference: string;
          qr_code: string | null;
          pix_copia_cola: string | null;
          status_pagamento: string;
          valor: number;
          payload_gateway: Json | null;
          created_at: string;
          updated_at: string | null;
          paid_at: string | null;
        };
        Insert: {
          id?: string;
          pedido_id?: string | null;
          numero_pedido: string;
          gateway: string;
          forma_pagamento: string;
          payment_id_gateway: string;
          external_reference: string;
          qr_code?: string | null;
          pix_copia_cola?: string | null;
          status_pagamento: string;
          valor: number;
          payload_gateway?: Json | null;
          created_at?: string;
          updated_at?: string | null;
          paid_at?: string | null;
        };
        Update: {
          id?: string;
          pedido_id?: string | null;
          numero_pedido?: string;
          gateway?: string;
          forma_pagamento?: string;
          payment_id_gateway?: string;
          external_reference?: string;
          qr_code?: string | null;
          pix_copia_cola?: string | null;
          status_pagamento?: string;
          valor?: number;
          payload_gateway?: Json | null;
          created_at?: string;
          updated_at?: string | null;
          paid_at?: string | null;
        };
      };
      abandoned_carts: {
        Row: {
          id: string;
          user_id: string | null;
          email: string | null;
          customer_name: string | null;
          customer_phone: string | null;
          cart_items: Json;
          cart_type: string | null;
          item_count: number;
          subtotal: number;
          total: number;
          status: string;
          source: string;
          whatsapp_payload: Json | null;
          email_payload: Json | null;
          last_activity_at: string;
          abandoned_at: string | null;
          recovered_at: string | null;
          converted_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          email?: string | null;
          customer_name?: string | null;
          customer_phone?: string | null;
          cart_items?: Json;
          cart_type?: string | null;
          item_count?: number;
          subtotal?: number;
          total?: number;
          status?: string;
          source?: string;
          whatsapp_payload?: Json | null;
          email_payload?: Json | null;
          last_activity_at?: string;
          abandoned_at?: string | null;
          recovered_at?: string | null;
          converted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          email?: string | null;
          customer_name?: string | null;
          customer_phone?: string | null;
          cart_items?: Json;
          cart_type?: string | null;
          item_count?: number;
          subtotal?: number;
          total?: number;
          status?: string;
          source?: string;
          whatsapp_payload?: Json | null;
          email_payload?: Json | null;
          last_activity_at?: string;
          abandoned_at?: string | null;
          recovered_at?: string | null;
          converted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      coupons: {
        Row: {
          id: string;
          code: string;
          name: string;
          description: string | null;
          type: string;
          discount_type: string;
          discount_value: number;
          minimum_order_value: number;
          max_discount_value: number | null;
          usage_limit: number | null;
          usage_count: number;
          per_user_limit: number;
          product_ids: string[];
          valid_from: string | null;
          valid_until: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          code: string;
          name: string;
          description?: string | null;
          type: string;
          discount_type: string;
          discount_value: number;
          minimum_order_value?: number;
          max_discount_value?: number | null;
          usage_limit?: number | null;
          usage_count?: number;
          per_user_limit?: number;
          product_ids?: string[];
          valid_from?: string | null;
          valid_until?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          code?: string;
          name?: string;
          description?: string | null;
          type?: string;
          discount_type?: string;
          discount_value?: number;
          minimum_order_value?: number;
          max_discount_value?: number | null;
          usage_limit?: number | null;
          usage_count?: number;
          per_user_limit?: number;
          product_ids?: string[];
          valid_from?: string | null;
          valid_until?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      coupon_redemptions: {
        Row: {
          id: string;
          coupon_id: string;
          order_id: string | null;
          user_id: string | null;
          email: string | null;
          coupon_code: string;
          discount_value: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          coupon_id: string;
          order_id?: string | null;
          user_id?: string | null;
          email?: string | null;
          coupon_code: string;
          discount_value?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          coupon_id?: string;
          order_id?: string | null;
          user_id?: string | null;
          email?: string | null;
          coupon_code?: string;
          discount_value?: number;
          created_at?: string;
        };
      };
      favorite_products: {
        Row: {
          id: string;
          user_id: string;
          product_id: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          product_id: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          product_id?: string;
          created_at?: string;
        };
      };
      user_events: {
        Row: {
          id: string;
          user_id: string | null;
          email: string | null;
          event_name: string;
          page: string | null;
          product_id: string | null;
          order_id: string | null;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          email?: string | null;
          event_name: string;
          page?: string | null;
          product_id?: string | null;
          order_id?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          email?: string | null;
          event_name?: string;
          page?: string | null;
          product_id?: string | null;
          order_id?: string | null;
          metadata?: Json;
          created_at?: string;
        };
      };
      marketing_events: {
        Row: {
          id: string;
          user_id: string | null;
          email: string | null;
          anonymous_id: string | null;
          event_name: string;
          standard_event: string | null;
          funnel_stage: string | null;
          page: string | null;
          product_id: string | null;
          order_id: string | null;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          email?: string | null;
          anonymous_id?: string | null;
          event_name: string;
          standard_event?: string | null;
          funnel_stage?: string | null;
          page?: string | null;
          product_id?: string | null;
          order_id?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          email?: string | null;
          anonymous_id?: string | null;
          event_name?: string;
          standard_event?: string | null;
          funnel_stage?: string | null;
          page?: string | null;
          product_id?: string | null;
          order_id?: string | null;
          metadata?: Json;
          created_at?: string;
        };
      };
      user_funnel_progress: {
        Row: {
          id: string;
          user_id: string | null;
          email: string | null;
          anonymous_id: string | null;
          current_stage: string;
          last_event_name: string;
          first_seen_at: string;
          last_seen_at: string;
          metadata: Json;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          email?: string | null;
          anonymous_id?: string | null;
          current_stage: string;
          last_event_name: string;
          first_seen_at?: string;
          last_seen_at?: string;
          metadata?: Json;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          email?: string | null;
          anonymous_id?: string | null;
          current_stage?: string;
          last_event_name?: string;
          first_seen_at?: string;
          last_seen_at?: string;
          metadata?: Json;
        };
      };
      whatsapp_message_logs: {
        Row: {
          id: string;
          user_id: string | null;
          order_id: string | null;
          phone: string;
          template_key: string;
          dedupe_key: string;
          provider: string;
          direction: string;
          status: string;
          provider_message_id: string | null;
          payload: Json;
          response: Json | null;
          sent_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          order_id?: string | null;
          phone: string;
          template_key: string;
          dedupe_key: string;
          provider: string;
          direction?: string;
          status?: string;
          provider_message_id?: string | null;
          payload?: Json;
          response?: Json | null;
          sent_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          order_id?: string | null;
          phone?: string;
          template_key?: string;
          dedupe_key?: string;
          provider?: string;
          direction?: string;
          status?: string;
          provider_message_id?: string | null;
          payload?: Json;
          response?: Json | null;
          sent_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      compradores_acesso: {
        Row: {
          id: string;
          email: string;
          nome: string | null;
          telefone: string | null;
          acesso_liberado: boolean;
          ultimo_numero_pedido: string | null;
          liberado_em: string | null;
          created_at: string;
          atualizado_em: string | null;
        };
        Insert: {
          id?: string;
          email: string;
          nome?: string | null;
          telefone?: string | null;
          acesso_liberado?: boolean;
          ultimo_numero_pedido?: string | null;
          liberado_em?: string | null;
          created_at?: string;
          atualizado_em?: string | null;
        };
        Update: {
          id?: string;
          email?: string;
          nome?: string | null;
          telefone?: string | null;
          acesso_liberado?: boolean;
          ultimo_numero_pedido?: string | null;
          liberado_em?: string | null;
          created_at?: string;
          atualizado_em?: string | null;
        };
      };
      visualizacoes_do_produto: {
        Row: {
          id: string;
          produto_id: string;
          visualizado_em: string;
          ip_address: string | null;
          user_agent: string | null;
        };
        Insert: {
          id?: string;
          produto_id: string;
          visualizado_em?: string;
          ip_address?: string | null;
          user_agent?: string | null;
        };
        Update: {
          id?: string;
          produto_id?: string;
          visualizado_em?: string;
          ip_address?: string | null;
          user_agent?: string | null;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
  };
}
